#contains various emep variables' parameters needed for QAQC

get_params_list = function() {
  
  MAP_TEMPLATE_BREAKS = c(0, 0.1,0.2,0.3,0.5,1,2,3,4,5,10,15,20,25,30,40,50,100, 1e6)
  MAP_TEMPLATE_BREAKS_HM = c(0.001,0.01,0.1,0.2,0.3,0.5,1,2,3,4,5,10,15,20,30,40,50,60,70,80,100,200)
  MAP_TEMPLATE_DIFF_BREAKS = seq(-10,10,1)
  MAP_TEMPLATE_DIFF_BREAKS_HM = seq(-10,10,1)
  
  VAR_PARAMS_LIST = list(Emis_mgm2_nox = list(map_levs = 100 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 20 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.0f',
                                              units = 'mg/m2',
                                              pretty_lab = 'NOx Emission',
                                              budg_factor = 1e6*1e-12,
                                              dsc_levs = c(0, seq(150,1500,150), 1e6),
                                              budg_units = 'Gg/yr',
                                              budg_stat = 'sum'),
                         Emis_mgm2_nh3 = list(map_levs = 500 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 20 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.0f',
                                              units = 'mg/m2',
                                              pretty_lab = 'NH3 Emission',
                                              budg_factor = 1e6*1e-12,
                                              dsc_levs = c(0, seq(150,1500,150), 1e6),
                                              budg_units = 'Gg/yr',
                                              budg_stat = 'sum'),
                         Emis_mgm2_sox = list(map_levs = 500 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 20 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.0f',
                                              units = 'mg/m2',
                                              pretty_lab = 'SOx Emission',
                                              budg_factor = 1e6*1e-12,
                                              dsc_levs = c(0, seq(150,1500,150), 1e6),
                                              budg_units = 'Gg/yr',
                                              budg_stat = 'sum'),
                         Emis_mgm2_BioNatC5H8 = list(map_levs = 500 * MAP_TEMPLATE_BREAKS,
                                                     map_difflevs = 20 * MAP_TEMPLATE_DIFF_BREAKS,
                                                     map_diffprecision = '%.0f',
                                                     units = 'mg/m2',
                                                     pretty_lab = 'Nat C5H8 Emission',
                                                     budg_factor = 1e6*1e-12,
                                                     dsc_levs = c(0, seq(150,1500,150), 1e6),
                                                     budg_units = 'Gg/yr',
                                                     budg_stat = 'sum'),
                         Emis_mgm2_BioNatBIOTERP = list(map_levs = NULL,
                                                        map_difflevs = NULL,
                                                        map_diffprecision = '%.0f',
                                                        units = 'mg/m2',
                                                        pretty_lab = 'BioNatBIOTERP Emission',
                                                        budg_factor = 1e6*1e-12,
                                                        dsc_levs = c(0, seq(150,1500,150), 1e6),
                                                        budg_units = 'Gg/yr',
                                                        budg_stat = 'sum'),
                         Emis_mgm2_BioNatNO = list(map_levs = NULL,
                                                   map_difflevs = NULL,
                                                   map_diffprecision = '%.0f',
                                                   units = 'mg/m2',
                                                   pretty_lab = 'BioNatNO Emission',
                                                   budg_factor = 1e6*1e-12,
                                                   dsc_levs = c(0, seq(150,1500,150), 1e6),
                                                   budg_units = 'Gg/yr',
                                                   budg_stat = 'sum'),
                         Emis_mgm2_DMS = list(map_levs = NULL,
                                              map_difflevs = NULL,
                                              map_diffprecision = '%.0f',
                                              units = 'mg/m2',
                                              pretty_lab = 'DMS Emission',
                                              budg_factor = 1e6*1e-12,
                                              dsc_levs = c(0, seq(150,1500,150), 1e6),
                                              budg_units = 'Gg/yr',
                                              budg_stat = 'sum'),
                         
                         SURF_ug_SO4 = list(map_levs = 0.2 * MAP_TEMPLATE_BREAKS,
                                            map_difflevs = 0.02 * MAP_TEMPLATE_DIFF_BREAKS,
                                            map_diffprecision = '%.2f',
                                            units = 'ug/m3',
                                            pretty_lab = 'SO42- Surface Concentration',
                                            budg_factor = 1,
                                            dsc_levs = c(0, seq(1,10,1), 1e6),
                                            budg_units = 'ug/m3',
                                            budg_stat = 'mean'),
                         SURF_ug_NH4_F = list(map_levs = 0.4 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 0.05 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.1f',
                                              units = 'ug/m3',
                                              pretty_lab = 'Surface NH4+ fine',
                                              budg_factor = 1,
                                              dsc_levs = c(0, seq(1,10,1), 1e6),
                                              budg_units = 'ug/m3',
                                              budg_stat = 'mean'),
                         SURF_ug_NH3 = list(map_levs = 0.2 * MAP_TEMPLATE_BREAKS,
                                            map_difflevs = 0.05 * MAP_TEMPLATE_DIFF_BREAKS,
                                            map_diffprecision = '%.1f',
                                            units = 'ug/m3',
                                            pretty_lab = 'Surface NH3',
                                            budg_factor = 1,
                                            dsc_levs = c(0, seq(1,10,1), 1e6),
                                            budg_units = 'ug/m3',
                                            budg_stat = 'mean'),
                         SURF_ug_NO2 = list(map_levs = 2 * MAP_TEMPLATE_BREAKS,
                                            map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                            map_diffprecision = '%.1f',
                                            units = 'ug/m3',
                                            pretty_lab = 'Surface NO2',
                                            budg_factor = 1,
                                            dsc_levs = c(0, seq(1,10,1), 1e6),
                                            budg_units = 'ug/m3',
                                            budg_stat = 'mean'),
                         SURF_ug_NO = list(map_levs = NULL,
                                           map_difflevs = NULL,
                                           map_diffprecision = '%.1f',
                                           units = 'ug/m3',
                                           pretty_lab = 'Surface NO',
                                           budg_factor = 1,
                                           dsc_levs = c(0, seq(1,10,1), 1e6),
                                           budg_units = 'ug/m3',
                                           budg_stat = 'mean'),
                         SURF_ug_SO2 = list(map_levs = 0.2 * MAP_TEMPLATE_BREAKS,
                                            map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                            map_diffprecision = '%.1f',
                                            units = 'ug/m3',
                                            pretty_lab = 'Surface SO2',
                                            budg_factor = 1,
                                            dsc_levs = c(0, seq(1,10,1), 1e6),
                                            budg_units = 'ug/m3',
                                            budg_stat = 'mean'),
                         SURF_ug_HNO3 = list(map_levs = 0.1 * MAP_TEMPLATE_BREAKS,
                                             map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                             map_diffprecision = '%.2f',
                                             units = 'ug/m3',
                                             pretty_lab = 'Surface HNO3',
                                             budg_factor = 1,
                                             dsc_levs = c(0, seq(1,10,1), 1e6),
                                             budg_units = 'ug/m3',
                                             budg_stat = 'mean'),
                         SURF_ug_NO3_F = list(map_levs = 0.1 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.2f',
                                              units = 'ug/m3',
                                              pretty_lab = 'Surface NO3 fine',
                                              budg_factor = 1,
                                              dsc_levs = c(0, seq(1,10,1), 1e6),
                                              budg_units = 'ug/m3',
                                              budg_stat = 'mean'),
                         SURF_ug_NO3_C = list(map_levs = 0.1 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.2f',
                                              units = 'ug/m3',
                                              pretty_lab = 'Surface NO3 coarse',
                                              budg_factor = 1,
                                              dsc_levs = c(0, seq(1,10,1), 1e6),
                                              budg_units = 'ug/m3',
                                              budg_stat = 'mean'),
                         SURF_ug_PM25 = list(map_levs = 0.3 * MAP_TEMPLATE_BREAKS,
                                             map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                             map_diffprecision = '%.1f',
                                             units = 'ug/m3',
                                             pretty_lab = 'Surface PM2.5',
                                             budg_factor = 1,
                                             dsc_levs = c(0, seq(1,10,1), 1e6),
                                             budg_units = 'ug/m3',
                                             budg_stat = 'mean'),
                         SURF_ug_PM25_rh50 = list(map_levs = 0.3 * MAP_TEMPLATE_BREAKS,
                                                  map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                  map_diffprecision = '%.1f',
                                                  units = 'ug/m3',
                                                  pretty_lab = 'Surface PM2.5',
                                                  budg_factor = 1,
                                                  dsc_levs = c(0, seq(1,10,1), 1e6),
                                                  budg_units = 'ug/m3',
                                                  budg_stat = 'mean'),
                         SURF_ug_PM_PMFINE = list(map_levs = 0.3 * MAP_TEMPLATE_BREAKS,
                                                  map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                  map_diffprecision = '%.1f',
                                                  units = 'ug/m3',
                                                  pretty_lab = 'Surface PM_PMFINE',
                                                  budg_factor = 1,
                                                  dsc_levs = c(0, seq(1,10,1), 1e6),
                                                  budg_units = 'ug/m3',
                                                  budg_stat = 'mean'),
                         SURF_ug_PM10 = list(map_levs = 0.5 * MAP_TEMPLATE_BREAKS,
                                             map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                             map_diffprecision = '%.1f',
                                             units = 'ug/m3',
                                             pretty_lab = 'Surface PM10',
                                             budg_factor = 1, 
                                             dsc_levs = c(0, seq(1,10,1), 1e6),
                                             budg_units = 'ug/m3',
                                             budg_stat = 'mean'),
                         SURF_ug_PM10_rh50 = list(map_levs = 0.5 * MAP_TEMPLATE_BREAKS,
                                                  map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                  map_diffprecision = '%.1f',
                                                  units = 'ug/m3',
                                                  pretty_lab = 'Surface PM10',
                                                  budg_factor = 1, 
                                                  dsc_levs = c(0, seq(1,10,1), 1e6),
                                                  budg_units = 'ug/m3',
                                                  budg_stat = 'mean'),
                         SURF_ug_PM_PM10 = list(map_levs = 0.5 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.1f',
                                                units = 'ug/m3',
                                                pretty_lab = 'Surface PM_PM10',
                                                budg_factor = 1,
                                                dsc_levs = c(0, seq(1,10,1), 1e6),
                                                budg_units = 'ug/m3',
                                                budg_stat = 'mean'),
                         SURF_ppb_O3 = list(map_levs = seq(20,50,2),
                                            map_difflevs = 20 * MAP_TEMPLATE_DIFF_BREAKS,
                                            map_diffprecision = '%d',
                                            units = 'ppb',
                                            pretty_lab = 'Surface O3',
                                            budg_factor = 2,
                                            dsc_levs = c(0, seq(20,50,2), 1e6),
                                            budg_units = 'ug/m3',
                                            budg_stat = 'mean'),
                         SURF_ug_PPM25 = list(map_levs = 0.3 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.1f',
                                              units = 'ug/m3',
                                              pretty_lab = 'Surface PPM2.5',
                                              budg_factor = NULL,
                                              dsc_levs = NULL,
                                              budg_units = '---',
                                              budg_stat = NULL),
                         SURF_ug_PPM_C = list(map_levs = 0.5 * MAP_TEMPLATE_BREAKS,
                                              map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                              map_diffprecision = '%.1f',
                                              units = 'ug/m3',
                                              pretty_lab = 'Surface PPMc',
                                              budg_factor = NULL,
                                              dsc_levs = NULL,
                                              budg_units = '---',
                                              budg_stat = NULL),
                         SURF_ug_DUST_WB_F = list(map_levs = NULL,
                                                  map_difflevs = NULL,
                                                  map_diffprecision = '%.1f',
                                                  units = 'ug/m3',
                                                  pretty_lab = 'Surface DUST_WB_F',
                                                  budg_factor = 1,
                                                  dsc_levs = c(0, seq(1,10,1), 1e6),
                                                  budg_units = 'ug/m3',
                                                  budg_stat = 'mean'),
                         SURF_ug_DUST_WB_C = list(map_levs = NULL,
                                                  map_difflevs = NULL,
                                                  map_diffprecision = '%.1f',
                                                  units = 'ug/m3',
                                                  pretty_lab = 'Surface DUST_WB_C',
                                                  budg_factor = 1,
                                                  dsc_levs = c(0, seq(1,10,1), 1e6),
                                                  budg_units = 'ug/m3',
                                                  budg_stat = 'mean'),
                         SURF_ug_DUST_ROAD_F = list(map_levs = NULL,
                                                    map_difflevs = NULL,
                                                    map_diffprecision = '%.1f',
                                                    units = 'ug/m3',
                                                    pretty_lab = 'Surface DUST_ROAD_F',
                                                    budg_factor = 1,
                                                    dsc_levs = c(0, seq(1,10,1), 1e6),
                                                    budg_units = 'ug/m3',
                                                    budg_stat = 'mean'),
                         SURF_ug_DUST_ROAD_C = list(map_levs = NULL,
                                                    map_difflevs = NULL,
                                                    map_diffprecision = '%.1f',
                                                    units = 'ug/m3',
                                                    pretty_lab = 'Surface DUST_ROAD_C',
                                                    budg_factor = 1,
                                                    dsc_levs = c(0, seq(1,10,1), 1e6),
                                                    budg_units = 'ug/m3',
                                                    budg_stat = 'mean'),
                         SURF_ug_SEASALT_F = list(map_levs = NULL,
                                                  map_difflevs = NULL,
                                                  map_diffprecision = '%.1f',
                                                  units = 'ug/m3',
                                                  pretty_lab = 'Surface SEASALT_F',
                                                  budg_factor = 1,
                                                  dsc_levs = c(0, seq(1,10,1), 1e6),
                                                  budg_units = 'ug/m3',
                                                  budg_stat = 'mean'),
                         SURF_ug_SEASALT_C = list(map_levs = NULL,
                                                  map_difflevs = NULL,
                                                  map_diffprecision = '%.1f',
                                                  units = 'ug/m3',
                                                  pretty_lab = 'Surface SEASALT_C',
                                                  budg_factor = 1,
                                                  dsc_levs = c(0, seq(1,10,1), 1e6),
                                                  budg_units = 'ug/m3',
                                                  budg_stat = 'mean'),
                         SURF_ug_PM_ASOA = list(map_levs = NULL,
                                                map_difflevs = NULL,
                                                map_diffprecision = '%.1f',
                                                units = 'ug/m3',
                                                pretty_lab = 'Surface PM_ASOA',
                                                budg_factor = 1,
                                                dsc_levs = c(0, seq(1,10,1), 1e6),
                                                budg_units = 'ug/m3',
                                                budg_stat = 'mean'),
                         SURF_ug_PM_BSOA = list(map_levs = NULL,
                                                map_difflevs = NULL,
                                                map_diffprecision = '%.1f',
                                                units = 'ug/m3',
                                                pretty_lab = 'Surface PM_BSOA',
                                                budg_factor = 1,
                                                dsc_levs = c(0, seq(1,10,1), 1e6),
                                                budg_units = 'ug/m3',
                                                budg_stat = 'mean'),
                         SURF_ug_CD = list(map_levs = 1E-4 * MAP_TEMPLATE_BREAKS_HM,
                                           map_difflevs = 1E-4 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                           map_diffprecision = '%.3f',
                                           units = 'ug/m3',
                                           lab = 'Surface Cd Concentration',
                                           budg_factor = 1,
                                           dsc_levs = c(0, seq(1,10,1), 1e6),
                                           budg_units = 'ug/m3',
                                           budg_stat = 'mean'),
                         SURF_ug_CU = list(map_levs = 1E-3 * MAP_TEMPLATE_BREAKS_HM,
                                           map_difflevs = 1E-3 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                           map_diffprecision = '%.3f',
                                           units = 'ug/m3',
                                           lab = 'Surface Cu Concentration',
                                           budg_factor = 1,
                                           dsc_levs = c(0, seq(1,10,1), 1e6),
                                           budg_units = 'ug/m3',
                                           budg_stat = 'mean'),
                         SURF_ug_NI = list(map_levs = 1E-3 * MAP_TEMPLATE_BREAKS_HM,
                                           map_difflevs = 1E-3 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                           map_diffprecision = '%.3f',
                                           units = 'ug/m3',
                                           lab = 'Surface Ni Concentration',
                                           budg_factor = 1,
                                           dsc_levs = c(0, seq(1,10,1), 1e6),
                                           budg_units = 'ug/m3',
                                           budg_stat = 'mean'),
                         SURF_ug_PB = list(map_levs = 1E-3 * MAP_TEMPLATE_BREAKS_HM,
                                           map_difflevs = 1E-3 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                           map_diffprecision = '%.3f',
                                           units = 'ug/m3',
                                           lab = 'Surface PB Concentration',
                                           budg_factor = 1,
                                           dsc_levs = c(0, seq(1,10,1), 1e6),
                                           budg_units = 'ug/m3',
                                           budg_stat = 'mean'),
                         SURF_ug_ZN = list(map_levs = 1E-3 * MAP_TEMPLATE_BREAKS_HM,
                                           map_difflevs = 1E-3 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                           map_diffprecision = '%.3f',
                                           units = 'ug/m3',
                                           lab = 'Surface Zn Concentration',
                                           budg_factor = 1,
                                           dsc_levs = c(0, seq(1,10,1), 1e6),
                                           budg_units = 'ug/m3',
                                           budg_stat = 'mean'),
                         
                         DDEP_OXN_m2Grid = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.1f',
                                                units = 'mgN/m2',
                                                pretty_lab = 'Dry dep NOy',
                                                budg_factor = 1e6*1e-12,
                                                dsc_levs = c(0, seq(50,500,50), 1e6),
                                                budg_units = 'GgN/yr',
                                                budg_stat = 'sum'),
                         DDEP_SOX_m2Grid = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.1f',
                                                units = 'mgS/m2',
                                                pretty_lab = 'Dry dep SOx',
                                                budg_factor = 1e6*1e-12,
                                                dsc_levs = c(0, seq(50,500,50), 1e6),
                                                budg_units = 'GgS/yr',
                                                budg_stat = 'sum'),
                         DDEP_RDN_m2Grid = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.1f',
                                                units = 'mgN/m2',
                                                pretty_lab = 'Dry dep NHx',
                                                budg_factor = 1e6*1e-12,
                                                dsc_levs = c(0, seq(50,500,50), 1e6),
                                                budg_units = 'GgN/yr',
                                                budg_stat = 'sum'),
                         DDEP_OXN_m2Decid = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgN/m2',
                                                 pretty_lab = 'Dry dep NOy',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_SOX_m2Decid = list(map_levs = 20 * MAP_TEMPLATE_BREAKS, 
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgS/m2',
                                                 pretty_lab = 'Dry dep SOx',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_RDN_m2Decid = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgN/m2',
                                                 pretty_lab = 'Dry dep NHx',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_OXN_m2Seminat = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%1f',
                                                   units = 'mgN/m2',
                                                   pretty_lab = 'Dry dep NOy',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_SOX_m2Seminat = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgS/m2',
                                                   pretty_lab = 'Dry dep SOx',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_RDN_m2Seminat = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgN/m2',
                                                   pretty_lab = 'Dry dep NHx',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_OXN_m2Crops = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgN/m2',
                                                 pretty_lab = 'Dry dep NOy',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_SOX_m2Crops = list(map_levs = 20 * MAP_TEMPLATE_BREAKS, 
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgS/m2',
                                                 pretty_lab = 'Dry dep SOx',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_RDN_m2Crops = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgN/m2',
                                                 pretty_lab = 'Dry dep NHx',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_OXN_m2Conif = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgN/m2',
                                                 pretty_lab = 'Dry dep NOy',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_SOX_m2Conif = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgS/m2',
                                                 pretty_lab = 'Dry dep SOx',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_RDN_m2Conif = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                 map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                 map_diffprecision = '%.1f',
                                                 units = 'mgN/m2',
                                                 pretty_lab = 'Dry dep NHx',
                                                 budg_factor = NULL,
                                                 dsc_levs = NULL,
                                                 budg_units = '---',
                                                 budg_stat = NULL),
                         DDEP_OXN_m2Water_D = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgN/m2',
                                                   pretty_lab = 'Dry dep NOy',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_SOX_m2Water_D = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgS/m2',
                                                   pretty_lab = 'Dry dep SOx',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_RDN_m2Water_D = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgN/m2',
                                                   pretty_lab = 'Dry dep NHx',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_OXN_m2Urban = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgN/m2',
                                                   pretty_lab = 'Dry dep NOy',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_SOX_m2Urban = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgS/m2',
                                                   pretty_lab = 'Dry dep SOx',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_RDN_m2Urban = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                                   map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                                   map_diffprecision = '%.1f',
                                                   units = 'mgN/m2',
                                                   pretty_lab = 'Dry dep NHx',
                                                   budg_factor = NULL,
                                                   dsc_levs = NULL,
                                                   budg_units = '---',
                                                   budg_stat = NULL),
                         DDEP_NO2_m2Grid = list(map_levs = NULL,
                                                map_difflevs = NULL,
                                                map_diffprecision = '%.1f',
                                                units = '---',
                                                pretty_lab = 'Dry dep NO2',
                                                budg_factor = 1e6*1e-12,
                                                dsc_levs = c(0, seq(50,500,50), 1e6),
                                                budg_units = '---',
                                                budg_stat = 'sum'),
                         DDEP_SO2_m2Grid = list(map_levs = NULL,
                                                map_difflevs = NULL,
                                                map_diffprecision = '%.1f',
                                                units = '---',
                                                pretty_lab = 'Dry dep SO2',
                                                budg_factor = 1e6*1e-12,
                                                dsc_levs = c(0, seq(50,500,50), 1e6),
                                                budg_units = '---',
                                                budg_stat = 'sum'),
                         DDEP_NH3_m2Grid = list(map_levs = NULL,
                                                map_difflevs = NULL,
                                                map_diffprecision = '%.1f',
                                                units = '---',
                                                pretty_lab = 'Dry dep NH3',
                                                budg_factor = 1e6*1e-12,
                                                dsc_levs = c(0, seq(50,500,50), 1e6),
                                                budg_units = '---',
                                                budg_stat = 'sum'),
                         DDEP_PM25ONS_m2Grid = list(map_levs = NULL,
                                                    map_difflevs = NULL,
                                                    map_diffprecision = '%.1f',
                                                    units = '---',
                                                    pretty_lab = 'Dry dep PM2.5 ONS',
                                                    budg_factor = 1e6*1e-12,
                                                    dsc_levs = c(0, seq(50,500,50), 1e6),
                                                    budg_units = '---',
                                                    budg_stat = 'sum'),
                         DDEP_PM10ONS_m2Grid = list(map_levs = NULL,
                                                    map_difflevs = NULL,
                                                    map_diffprecision = '%.1f',
                                                    units = '---',
                                                    pretty_lab = 'Dry dep PM10 ONS',
                                                    budg_factor = 1e6*1e-12,
                                                    dsc_levs = c(0, seq(50,500,50), 1e6),
                                                    budg_units = '---',
                                                    budg_stat = 'sum'),
                         DDEP_SO4_m2Grid = list(map_levs = NULL,
                                                map_difflevs = NULL,
                                                map_diffprecision = '%.1f',
                                                units = '---',
                                                pretty_lab = 'Dry dep SO4',
                                                budg_factor = 1e6*1e-12,
                                                dsc_levs = c(0, seq(50,500,50), 1e6),
                                                budg_units = '---',
                                                budg_stat = 'sum'),
                         DDEP_NO3_F_m2Grid = list(map_levs = NULL,
                                                  map_difflevs = NULL,
                                                  map_diffprecision = '%.1f',
                                                  units = '---',
                                                  pretty_lab = 'Dry dep NO3 fine',
                                                  budg_factor = 1e6*1e-12,
                                                  dsc_levs = c(0, seq(50,500,50), 1e6),
                                                  budg_units = '---',
                                                  budg_stat = 'sum'),
                         DDEP_NO3_C_m2Grid = list(map_levs = NULL,
                                                  map_difflevs = NULL,
                                                  map_diffprecision = '%.1f',
                                                  units = '---',
                                                  pretty_lab = 'Dry dep NO3 coarse',
                                                  budg_factor = 1e6*1e-12,
                                                  dsc_levs = c(0, seq(50,500,50), 1e6),
                                                  budg_units = '---',
                                                  budg_stat = 'sum'),
                         DDEP_NH4_F_m2Grid = list(map_levs = NULL,
                                                  map_difflevs = NULL,
                                                  map_diffprecision = '%.1f',
                                                  units = '---',
                                                  pretty_lab = 'Dry dep NH4 fine',
                                                  budg_factor = 1e6*1e-12,
                                                  dsc_levs = c(0, seq(50,500,50), 1e6),
                                                  budg_units = '---',
                                                  budg_stat = 'sum'),
                         DDEP_O3_m2Grid = list(map_levs = NULL,
                                               map_difflevs = NULL,
                                               map_diffprecision = '%.1f',
                                               units = '---',
                                               pretty_lab = 'Dry dep O3',
                                               budg_factor = 1e6*1e-12,
                                               dsc_levs = c(0, seq(50,500,50), 1e6),
                                               budg_units = '---',
                                               budg_stat = 'sum'),
                         DDEP_CD_m2Grid = list(map_levs = 1E-3 * MAP_TEMPLATE_BREAKS_HM,
                                               map_difflevs = 1E-3 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                               map_diffprecision = '%.3f',
                                               units = 'ng/m2',
                                               pretty_lab = 'Dry dep Cd',
                                               budg_factor = 1,
                                               dsc_levs = c(0, seq(50,500,50), 1e6),
                                               budg_units = '---',
                                               budg_stat = 'sum'),
                         DDEP_CU_m2Grid = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
                                               map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                               map_diffprecision = '%.3f',
                                               units = 'mg/m2',
                                               pretty_lab = 'Dry dep Cu',
                                               budg_factor = 1,
                                               dsc_levs = c(0, seq(50,500,50), 1e6),
                                               budg_units = 'mg/m2',
                                               budg_stat = 'sum'),
                         DDEP_NI_m2Grid = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
                                               map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                               map_diffprecision = '%.3f',
                                               units = 'mg/m2',
                                               pretty_lab = 'Dry dep Ni',
                                               budg_factor = 1,
                                               dsc_levs = c(0, seq(50,500,50), 1e6),
                                               budg_units = 'mg/m2',
                                               budg_stat = 'sum'),
                         DDEP_PB_m2Grid = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
                                               map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                               map_diffprecision = '%.3f',
                                               units = 'mg/m2',
                                               pretty_lab = 'Dry dep Pb',
                                               budg_factor = 1,
                                               dsc_levs = c(0, seq(50,500,50), 1e6),
                                               budg_units = 'mg/m2',
                                               budg_stat = 'sum'),
                         DDEP_ZN_m2Grid = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
                                               map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                               map_diffprecision = '%.3f',
                                               units = 'mg/m2',
                                               pretty_lab = 'Dry dep ZN',
                                               budg_factor = 1,
                                               dsc_levs = c(0, seq(50,500,50), 1e6),
                                               budg_units = 'mg/m2',
                                               budg_stat = 'sum'),
                         
                         WDEP_OXN = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                         map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                         map_diffprecision = '%.1f',
                                         units = 'mgN/m2',
                                         pretty_lab = 'Oxidised N Wet Deposition',
                                         budg_factor = 1e6*1e-12,
                                         dsc_levs = c(0, seq(50,500,50), 1e6),
                                         budg_units = 'GgN/yr',
                                         budg_stat = 'sum'),
                         WDEP_SOX = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                         map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                         map_diffprecision = '%.1f',
                                         units = 'mgS/m2',
                                         pretty_lab = 'SOx Wet Deposition',
                                         budg_factor = 1e6*1e-12,
                                         dsc_levs = c(0, seq(50,500,50), 1e6),
                                         budg_units = 'GgS/yr',
                                         budg_stat = 'sum'),
                         WDEP_RDN = list(map_levs = 20 * MAP_TEMPLATE_BREAKS,
                                         map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
                                         map_diffprecision = '%.1f',
                                         units = 'mgN/m2',
                                         pretty_lab = 'Reduced N Wet Deposition',
                                         budg_factor = 1e6*1e-12,
                                         dsc_levs = c(0, seq(50,500,50), 1e6),
                                         budg_units = 'GgN/yr',
                                         budg_stat = 'sum'),
                         WDEP_PREC = list(map_levs = NULL,
                                          map_difflevs = NULL,
                                          map_diffprecision = '%d',
                                          units = 'mm',
                                          pretty_lab = 'Precipitation',
                                          budg_factor = 1,
                                          dsc_levs = c(0, seq(100, 2500, 100), 1e6),
                                          budg_units = 'mm',
                                          budg_stat = 'mean'),
                         WDEP_O3 = list(map_levs = NULL,
                                        map_difflevs = NULL,
                                        map_diffprecision = '%.1f',
                                        units = NULL,
                                        pretty_lab = 'O3 Wet Deposition',
                                        budg_factor = NULL,
                                        dsc_levs = c(0, seq(50,500,50), 1e6),
                                        budg_units = NULL,
                                        budg_stat = 'sum'),
                         WDEP_NO2 = list(map_levs = NULL,
                                         map_difflevs = NULL,
                                         map_diffprecision = '%.1f',
                                         units = 'mgN/m2',
                                         pretty_lab = 'NO2 Wet Deposition',
                                         budg_factor = 1e6*1e-12,
                                         dsc_levs = c(0, seq(50,500,50), 1e6),
                                         budg_units = 'GgN/yr',
                                         budg_stat = 'sum'),
                         WDEP_SO2 = list(map_levs = NULL,
                                         map_difflevs = NULL,
                                         map_diffprecision = '%.1f',
                                         units = 'mgS/m2',
                                         pretty_lab = 'SO2 Wet Deposition',
                                         budg_factor = 1e6*1e-12,
                                         dsc_levs = c(0, seq(50,500,50), 1e6),
                                         budg_units = 'GgS/yr',
                                         budg_stat = 'sum'),
                         WDEP_NH3 = list(map_levs = NULL,
                                         map_difflevs = NULL,
                                         map_diffprecision = '%.1f',
                                         units = 'mgN/m2',
                                         pretty_lab = 'NH3 Wet Deposition',
                                         budg_factor = 1e6*1e-12,
                                         dsc_levs = c(0, seq(50,500,50), 1e6),
                                         budg_units = 'GgN/yr',
                                         budg_stat = 'sum'),
                         WDEP_SO4 = list(map_levs = NULL,
                                         map_difflevs = NULL,
                                         map_diffprecision = '%.1f',
                                         units = 'mgS/m2',
                                         pretty_lab = 'SO42- Wet Deposition',
                                         budg_factor = 1e6*1e-12,
                                         dsc_levs = c(0, seq(50,500,50), 1e6),
                                         budg_units = 'GgS/yr',
                                         budg_stat = 'sum'),
                         WDEP_NO3_F = list(map_levs = NULL,
                                           map_difflevs = NULL,
                                           map_diffprecision = '%.1f',
                                           units = 'mgN/m2',
                                           pretty_lab = 'NO3 fine Wet Deposition',
                                           budg_factor = 1e6*1e-12,
                                           dsc_levs = c(0, seq(50,500,50), 1e6),
                                           budg_units = 'GgN/yr',
                                           budg_stat = 'sum'),
                         WDEP_NO3_c = list(map_levs = NULL,
                                           map_difflevs = NULL,
                                           map_diffprecision = '%.1f',
                                           units = 'mgN/m2',
                                           pretty_lab = 'NO3 coarse Wet Deposition',
                                           budg_factor = 1e6*1e-12,
                                           dsc_levs = c(0, seq(50,500,50), 1e6),
                                           budg_units = 'GgN/yr',
                                           budg_stat = 'sum'),
                         WDEP_NH3 = list(map_levs = NULL,
                                           map_difflevs = NULL,
                                           map_diffprecision = '%.2f',
                                           units = 'mgN/m2',
                                           pretty_lab = 'Wet dep NH3',
                                           budg_factor = 1e6*1e-12,
                                           dsc_levs = c(0, seq(50,500,50), 1e6),
                                           budg_units = '---',
                                           budg_stat = 'sum'),
                         WDEP_NH4_F = list(map_levs = NULL,
                                           map_difflevs = NULL,
                                           map_diffprecision = '%.2f',
                                           units = 'mgN/m2',
                                           pretty_lab = 'NH4+ fine Wet Deposition',
                                           budg_factor = 1e6*1e-12,
                                           dsc_levs = c(0, seq(50,500,50), 1e6),
                                           budg_units = 'GgN/yr',
                                           budg_stat = 'sum'),
                         WDEP_PM25ONS = list(map_levs = NULL,
                                             map_difflevs = NULL,
                                             map_diffprecision = '%.2f',
                                             units = NULL,
                                             pretty_lab = 'Wet dep PM25 ONS',
                                             budg_factor = 1e6*1e-12,
                                             dsc_levs = c(0, seq(50,500,50), 1e6),
                                             budg_units = NULL,
                                             budg_stat = 'sum'),
                         WDEP_PM10ONS = list(map_levs = NULL,
                                             map_difflevs = NULL,
                                             map_diffprecision = '%.2f',
                                             units = NULL,
                                             pretty_lab = 'Wet dep PM10 ONS',
                                             budg_factor = 1e6*1e-12,
                                             dsc_levs = c(0, seq(50,500,50), 1e6),
                                             budg_units = '---',
                                             budg_stat = 'sum'),
                         WDEP_CD = list(map_levs = 1E-3 * MAP_TEMPLATE_BREAKS_HM,
										map_difflevs = 1E-3 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                        map_diffprecision = '%.2f',
                                        units = 'mg/m3',
                                        pretty_lab = 'Wet dep Cd',
                                        budg_factor = 1e6*1e-12,
                                        dsc_levs = c(0, seq(50,500,50), 1e6),
                                        budg_units = 'mg/m3',
                                        budg_stat = 'sum'),
                         WDEP_CU = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
									    map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                        map_diffprecision = '%.2f',
                                        units = 'mg/m3',
                                        pretty_lab = 'Wet dep Cu',
                                        budg_factor = 1e6*1e-12,
                                        dsc_levs = c(0, seq(50,500,50), 1e6),
                                        budg_units = 'mg/m3',
                                        budg_stat = 'sum'),
                         WDEP_NI = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
									    map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                        map_diffprecision = '%.2f',
                                        units = 'mg/m3',
                                        pretty_lab = 'Wet dep Ni',
                                        budg_factor = 1e6*1e-12,
                                        dsc_levs = c(0, seq(50,500,50), 1e6),
                                        budg_units = 'mg/m3',
                                        budg_stat = 'sum'),
                         WDEP_PB = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
									    map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                        map_diffprecision = '%.2f',
                                        units = 'mg/m3',
                                        pretty_lab = 'Wet dep Pb',
                                        budg_factor = 1e6*1e-12,
                                        dsc_levs = c(0, seq(50,500,50), 1e6),
                                        budg_units = 'mg/m3',
                                        budg_stat = 'sum'),
                         WDEP_ZN = list(map_levs = 1E-1 * MAP_TEMPLATE_BREAKS_HM,
									    map_difflevs = 1E-1 * MAP_TEMPLATE_DIFF_BREAKS_HM,
                                        map_diffprecision = '%.2f',
                                        units = 'mg/m3',
                                        pretty_lab = 'Wet dep Zn',
                                        budg_factor = 1e6*1e-12,
                                        dsc_levs = c(0, seq(50,500,50), 1e6),
                                        budg_units = 'mg/m3',
                                        budg_stat = 'sum'),
                         
                         VG_SO2_Grid = list(map_levs = NULL,
                                            map_difflevs = NULL,
                                            map_diffprecision = '%.1f',
                                            units = '---',
                                            pretty_lab = 'VG_SO2',
                                            budg_factor = 1e6*1e-12,
                                            dsc_levs = c(0, seq(0.2,2,0.2), 1e6),
                                            budg_units = 'cm/s',
                                            budg_stat = 'mean'),
                         VG_O3_Grid = list(map_levs = NULL,
                                           map_difflevs = NULL,
                                           map_diffprecision = '%.1f',
                                           units = '---',
                                           pretty_lab = 'VG_O3',
                                           budg_factor = 1e6*1e-12,
                                           dsc_levs = c(0, seq(0.2,2,0.2), 1e6),
                                           budg_units = 'cm/s',
                                           budg_stat = 'mean'),
                         VG_NH3_Grid = list(map_levs = NULL,
                                            map_difflevs = NULL,
                                            map_diffprecision = '%.1f',
                                            units = '---',
                                            pretty_lab = 'VG_NH3',
                                            budg_factor = 1e6*1e-12,
                                            dsc_levs = c(0, seq(0.2,2,0.2), 1e6),
                                            budg_units = 'cm/s',
                                            budg_stat = 'mean'),
                         VG_HNO3_Grid = list(map_levs = NULL,
                                             map_difflevs = NULL,
                                             map_diffprecision = '%.1f',
                                             units = '---',
                                             pretty_lab = 'VG_HNO3',
                                             budg_factor = 1e6*1e-12,
                                             dsc_levs = c(0, seq(0.2,2,0.2), 1e6),
                                             budg_units = 'cm/s',
                                             budg_stat = 'mean'),
                         VG_NO3_F_Grid = list(map_levs = NULL, 
                                              map_difflevs = NULL,
                                              map_diffprecision = '%.1f',
                                              units = '---',
                                              pretty_lab = 'VG_NO3 fine',
                                              budg_factor = 1e6*1e-12,
                                              dsc_levs = c(0, seq(0.2,2,0.2), 1e6),
                                              budg_units = 'cm/s',
                                              budg_stat = 'mean'),
                         VG_NO3_C_Grid = list(map_levs = NULL,
                                              map_difflevs = NULL,
                                              map_diffprecision = '%.1f',
                                              units = '---',
                                              pretty_lab = 'VG_NO3 coarse',
                                              budg_factor = 1e6*1e-12,
                                              dsc_levs = c(0, seq(0.2,2,0.2), 1e6),
                                              budg_units = 'cm/s',
                                              budg_stat = 'mean'),
                         VG_SO4_Grid = list(map_levs = NULL,
                                            map_difflevs = NULL,
                                            map_diffprecision = '%.1f',
                                            units = '---',
                                            pretty_lab = 'VG_SO4',
                                            budg_factor = 1e6*1e-12,
                                            dsc_levs = c(0, seq(0.2,2,0.2), 1e6),
                                            budg_units = 'cm/s',
                                            budg_stat = 'mean'),
                         
                         Area_Conif_Frac = list(map_levs = 0.01 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.2f',
                                                units = '1',
                                                pretty_lab = 'Conif',
                                                budg_factor = NULL,
                                                dsc_levs = NULL,
                                                budg_units = '---',
                                                budg_stat = NULL),
                         Area_Decid_Frac = list(map_levs = 0.01 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.2f',
                                                units = '1',
                                                pretty_lab = 'Decid',
                                                budg_factor = NULL,
                                                dsc_levs = NULL,
                                                budg_units = '---',
                                                budg_stat = NULL),
                         Area_Seminat_Frac = list(map_levs = 0.01 * MAP_TEMPLATE_BREAKS,
                                                  map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                                  map_diffprecision = '%.2f',
                                                  units = '1',
                                                  pretty_lab = 'Seminat',
                                                  budg_factor = NULL,
                                                  dsc_levs = NULL,
                                                  budg_units = '---',
                                                  budg_stat = NULL),
                         Area_Crops_Frac = list(map_levs = 0.01 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.2f',
                                                units = '1',
                                                pretty_lab = 'Crops',
                                                budg_factor = NULL,
                                                dsc_levs = NULL,
                                                budg_units = '---',
                                                budg_stat = NULL),
                         Area_Desert_Frac = list(map_levs = 0.01 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.2f',
                                                units = '1',
                                                pretty_lab = 'Desert',
                                                budg_factor = NULL,
                                                dsc_levs = NULL,
                                                budg_units = '---',
                                                budg_stat = NULL),
                         Area_Urban_Frac = list(map_levs = 0.01 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.2f',
                                                units = '1',
                                                pretty_lab = 'Urban',
                                                budg_factor = NULL,
                                                dsc_levs = NULL,
                                                budg_units = '---',
                                                budg_stat = NULL),
                         Area_Water_D_Frac = list(map_levs = 0.01 * MAP_TEMPLATE_BREAKS,
                                                map_difflevs = 0.01 * MAP_TEMPLATE_DIFF_BREAKS,
                                                map_diffprecision = '%.2f',
                                                units = '1',
                                                pretty_lab = 'Water',
                                                budg_factor = NULL,
                                                dsc_levs = NULL,
                                                budg_units = '---',
                                                budg_stat = NULL),
                         Area_Grid_km2 = list(map_levs = NULL,
                                              map_difflevs = NULL,
                                              map_diffprecision = '%.1f',
                                              units = 'km2',
                                              pretty_lab = 'Area_Grid',
                                              budg_factor = 1,
                                              dsc_levs = c(0, seq(100,2000,100), 1e6),
                                              budg_units = 'km2',
                                              budg_stat = 'mean'),
									#uEMEP_vars
									nox_concentration = list(map_levs = 4 * MAP_TEMPLATE_BREAKS,
									                         map_difflevs = 2 * MAP_TEMPLATE_DIFF_BREAKS,
									                         map_diffprecision = '%.1f',
									                         units = 'ug/m3',
									                         pretty_lab = 'Surface NO2',
									                         budg_factor = 1,
									                         dsc_levs = c(0, seq(1,10,1), 1e6),
									                         budg_units = 'ug/m3',
									                         budg_stat = 'mean'),
						  		no2_concentration = list(map_levs = 2 * MAP_TEMPLATE_BREAKS,
    										                   map_difflevs = 1 * MAP_TEMPLATE_DIFF_BREAKS,
    										                   map_diffprecision = '%.1f',
    										                   units = 'ug/m3',
    										                   pretty_lab = 'Surface NO2',
    										                   budg_factor = 1,
    										                   dsc_levs = c(0, seq(1,10,1), 1e6),
    										                   budg_units = 'ug/m3',
    										                   budg_stat = 'mean'),
									o3_concentration = list(map_levs = seq(40,100,4),
									                        map_difflevs = 20 * MAP_TEMPLATE_DIFF_BREAKS,
									                        map_diffprecision = '%d',
									                        units = 'ug/m3',
									                        pretty_lab = 'Surface O3',
									                        budg_factor = 1,
									                        dsc_levs = c(0, seq(20,50,2), 1e6),
									                        budg_units = 'ug/m3',
									                        budg_stat = 'mean'),
									pm25_concentration = list(map_levs = 0.3 * MAP_TEMPLATE_BREAKS,
									                          map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
									                          map_diffprecision = '%.1f',
									                          units = 'ug/m3',
									                          pretty_lab = 'Surface PM_PMFINE',
									                          budg_factor = 1,
									                          dsc_levs = c(0, seq(1,10,1), 1e6),
									                          budg_units = 'ug/m3',
									                          budg_stat = 'mean'),
									pm10_concentration = list(map_levs = 0.5 * MAP_TEMPLATE_BREAKS,
      									                    map_difflevs = 0.1 * MAP_TEMPLATE_DIFF_BREAKS,
      									                    map_diffprecision = '%.1f',
      									                    units = 'ug/m3',
      									                    pretty_lab = 'Surface PM10',
      									                    budg_factor = 1, 
      									                    dsc_levs = c(0, seq(1,10,1), 1e6),
      									                    budg_units = 'ug/m3',
      									                    budg_stat = 'mean')
									
										
										)
  
  VAR_PARAMS_LIST
}

get_obs_var_params_list = function() {
  list(no = list(poll_col = '#984ea3',
                 poll_fill = '#decbe4',
                 lab_unit ='NO~(mu*g~m^-3)'),
       no2 = list(poll_col = '#377eb8',
                  poll_fill = '#b3cde3',
                  lab_unit = 'NO[2]~(mu*g~m^-3)'),
       o3 = list(poll_col = '#4daf4a',
                 poll_fill = '#ccebc5',
                 lab_unit = 'O[3]~(mu*g~m^-3)'),
       ox = list(poll_col = '#008b8b',
                 poll_fill = '#D1EEEE',
                 lab_unit = 'O[x]~(mu*g~m^-3)'),
       'ox(ppb)' = list(poll_col = '#008b8b',
                 poll_fill = '#D1EEEE',
                 lab_unit = 'O[x]~(ppb)'),
       nh3 = list(poll_col = '#e41a1c',
                  poll_fill = '#fbb4ae',
                  lab_unit = 'NH[3]~(mu*g~m^-3)'),
       so2 = list(poll_col = '#f781bf',
                  poll_fill = '#fddaec',
                  lab_unit = 'SO[2]~(mu*g~m^-3)'),
       pm2.5 = list(poll_col = '#ff7f00',
                    poll_fill = '#fed9a6',
                    lab_unit = 'PM[2.5]~(mu*g~m^-3)'),
       pm25 = list(poll_col = '#ff7f00',
                    poll_fill = '#fed9a6',
                    lab_unit = 'PM[2.5]~(mu*g~m^-3)'),
       pm10 = list(poll_col = '#a65628',
                   poll_fill = '#e5d8bd',
                   lab_unit ='PM[10]~(mu*g~m^-3)')
       )
  
}


